### ISSUE TITLE
Error  on running make deploy on Apple M1 Pro Monterrey

### ISSUE THREAD

**Issue by saurabhdes** [trstringer/otel-shopping-cart#1]
Getting below error on running `make deploy` on Apple M1 Pro Monterrey. Seems to be due to grpcio , i tried downgrading it but that didn't help

```
=> ERROR [4/4] RUN apk add --no-cache --update py-pip python3 &&     pip install -r ./requirements.txt                                                                                                                 10.4s
------
 > [4/4] RUN apk add --no-cache --update py-pip python3 &&     pip install -r ./requirements.txt:
#8 0.208 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/aarch64/APKINDEX.tar.gz
#8 0.734 fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/aarch64/APKINDEX.tar.gz
#8 1.046 (1/25) Installing libbz2 (1.0.8-r1)
#8 1.078 (2/25) Installing expat (2.4.8-r0)
#8 1.116 (3/25) Installing libffi (3.4.2-r1)
#8 1.145 (4/25) Installing gdbm (1.23-r0)
#8 1.174 (5/25) Installing xz-libs (5.2.5-r1)
#8 1.206 (6/25) Installing libgcc (11.2.1_git20220219-r2)
#8 1.237 (7/25) Installing libstdc++ (11.2.1_git20220219-r2)
#8 1.315 (8/25) Installing mpdecimal (2.5.1-r1)
#8 1.348 (9/25) Installing ncurses-terminfo-base (6.3_p20220521-r0)
#8 1.382 (10/25) Installing ncurses-libs (6.3_p20220521-r0)
#8 1.434 (11/25) Installing readline (8.1.2-r0)
#8 1.473 (12/25) Installing sqlite-libs (3.38.5-r0)
#8 1.547 (13/25) Installing python3 (3.10.5-r0)
#8 2.896 (14/25) Installing py3-contextlib2 (21.6.0-r2)
#8 2.922 (15/25) Installing py3-tomli (2.0.1-r1)
#8 2.950 (16/25) Installing py3-pep517 (0.12.0-r2)
#8 2.992 (17/25) Installing py3-six (1.16.0-r1)
#8 3.029 (18/25) Installing py3-retrying (1.3.3-r3)
#8 3.049 (19/25) Installing py3-appdirs (1.4.4-r3)
#8 3.076 (20/25) Installing py3-more-itertools (8.13.0-r0)
#8 3.110 (21/25) Installing py3-ordered-set (4.0.2-r3)
#8 3.135 (22/25) Installing py3-parsing (2.4.7-r3)
#8 3.174 (23/25) Installing py3-packaging (21.3-r0)
#8 3.207 (24/25) Installing py3-setuptools (59.4.0-r0)
#8 3.308 (25/25) Installing py3-pip (22.1.1-r0)
#8 4.166 Executing busybox-1.35.0-r17.trigger
#8 4.172 OK: 76 MiB in 39 packages
#8 5.292 Collecting astroid==2.11.7
#8 5.459   Downloading astroid-2.11.7-py3-none-any.whl (251 kB)
#8 5.529      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.2/251.2 kB 3.7 MB/s eta 0:00:00
#8 5.573 Collecting backoff==1.11.1
#8 5.598   Downloading backoff-1.11.1-py2.py3-none-any.whl (13 kB)
#8 5.643 Collecting click==8.1.3
#8 5.675   Downloading click-8.1.3-py3-none-any.whl (96 kB)
#8 5.684      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 kB 12.9 MB/s eta 0:00:00
#8 5.720 Collecting Deprecated==1.2.13
#8 5.749   Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
#8 5.789 Collecting dill==0.3.5.1
#8 5.811   Downloading dill-0.3.5.1-py2.py3-none-any.whl (95 kB)
#8 5.830      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.8/95.8 kB 9.3 MB/s eta 0:00:00
#8 5.885 Collecting Flask==2.1.3
#8 5.909   Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
#8 5.922      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 9.4 MB/s eta 0:00:00
#8 5.958 Collecting googleapis-common-protos==1.56.4
#8 5.983   Downloading googleapis_common_protos-1.56.4-py2.py3-none-any.whl (211 kB)
#8 6.008      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.7/211.7 kB 8.9 MB/s eta 0:00:00
#8 6.487 Collecting grpcio==1.47.0
#8 6.510   Downloading grpcio-1.47.0.tar.gz (21.9 MB)
#8 8.577      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.9/21.9 MB 10.5 MB/s eta 0:00:00
#8 9.835   Preparing metadata (setup.py): started
#8 9.995   Preparing metadata (setup.py): finished with status 'error'
#8 10.00   error: subprocess-exited-with-error
#8 10.00
#8 10.00   × python setup.py egg_info did not run successfully.
#8 10.00   │ exit code: 1
#8 10.00   ╰─> [12 lines of output]
#8 10.00       Traceback (most recent call last):
#8 10.00         File "<string>", line 2, in <module>
#8 10.00         File "<pip-setuptools-caller>", line 34, in <module>
#8 10.00         File "/tmp/pip-install-wxxa16xz/grpcio_63dcbf79ded14ca9b1c9e116205b28cf/setup.py", line 263, in <module>
#8 10.00           if check_linker_need_libatomic():
#8 10.00         File "/tmp/pip-install-wxxa16xz/grpcio_63dcbf79ded14ca9b1c9e116205b28cf/setup.py", line 210, in check_linker_need_libatomic
#8 10.00           cpp_test = subprocess.Popen(cxx + ['-x', 'c++', '-std=c++14', '-'],
#8 10.00         File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
#8 10.00           self._execute_child(args, executable, preexec_fn, close_fds,
#8 10.00         File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
#8 10.00           raise child_exception_type(errno_num, err_msg, err_filename)
#8 10.00       FileNotFoundError: [Errno 2] No such file or directory: 'c++'
#8 10.00       [end of output]
#8 10.00
#8 10.00   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 10.00 error: metadata-generation-failed
#8 10.00
#8 10.00 × Encountered error while generating package metadata.
#8 10.00 ╰─> See above for output.
#8 10.00
#8 10.00 note: This is an issue with the package mentioned above, not pip.
#8 10.00 hint: See above for details.
------
executor failed running [/bin/sh -c apk add --no-cache --update py-pip python3 &&     pip install -r ./requirements.txt]: exit code: 1
make: *** [build-image-price] Error 1
```

**Comment by saurabhdes** [comment]
The issue was with alpine on grpcio . I tried `apk add linux-headers` as per  https://stackoverflow.com/questions/72335807/pip3-install-grpcio-fails-on-alpine-linux  but that didn't work. 

But i resolved it by changing the base image from alpine to python:3.10-slim
Below is the updated code

```
FROM python:3.10-slim

WORKDIR /var/app

COPY \
    ./external/price_server \
    /var/app/

RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt

ENTRYPOINT ["gunicorn", "app:app"]
```
